[workspace]
members = ["del-canvas-cpu", "del-canvas-cpu-gl"]
resolver = "2"
exclude = ["del-canvas-cuda-kernel", "del-canvas-cuda"]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "drawing primitives (e.g., triangles and lines) to bitmap images and gif animation."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
num-traits = "0.2.19"
png = "0.17.13"
gif = "0.13.1"
image = "0.25.1"
nalgebra = "0.33.0"
rand = "0.8.5"
rayon = "1.10.0"
anyhow = "1.0.86"
arrayref = "0.3.8"
itertools = "0.13.0"
rand_chacha = "0.3.1"
slice-of-array = "0.3.2"
# internal
del-canvas-core = { path = "del-canvas-cpu" }

 del-geo-core = { path = "../del-geo/del-geo-core"} # "0.1.29" #
 del-geo-nalgebra ={ path = "../del-geo/del-geo-nalgebra"} #  "0.1.29" #
 del-msh-core = { path = "../del-msh/del-msh-core"} # "0.1.34" #
 del-gl-core = {path = "../del-gl/del-gl-core" }
 del-winit-glutin = {path = "../del-gl/del-winit-glutin"}
#
#del-geo-core = { git = "https://github.com/nobuyuki83/del-geo.git" }
#del-geo-nalgebra = { git = "https://github.com/nobuyuki83/del-geo.git" }
#del-msh-core = { git = "https://github.com/nobuyuki83/del-msh.git" }
#del-gl-core = {git = "https://github.com/nobuyuki83/del-gl.git"}
#del-winit-glutin = {git = "https://github.com/nobuyuki83/del-gl.git"}
