[package]
name = "del-canvas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
png = "0.17.10"
gif = "0.12.0"
nalgebra = "0.32.3"