[package]
name = "del-canvas-cuda"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
num-traits = "0.2.19"

[build-dependencies]
cc = "1.1.8"
